export function createShellState({ settings, lastNewsSearchAt = null, subtitles2 } = {}) {
  return {
    settings,
    items: [],
    queue: [],
    dismissedQueueJobs: new Set(),
    searchRefreshRunning: false,
    searchRefreshStatus: 'Puede tardar aproximadamente 3 minutos.',
    searchRefreshStatusKind: 'idle',
    searchRefreshRunId: null,
    searchRefreshPollingToken: null,
    searchRefreshPollingErrorStreak: 0,
    lastSearchRefresh: null,
    lastNewsSearchAt,
    selectedCardId: null,
    selectedTopic: null,
    deletingSource: false,
    currentView: 'approval',
    scriptDrafts: [],
    selectedScript: null,
    scriptEditorDirty: false,
    scriptPublishJob: null,
    scriptPublishPollingTimer: null,
    scriptPublishPollingInFlight: false,
    dismissedProcessedScripts: new Set(),
    savingScript: false,
    publishingScript: false,
    downloadingScript: false,
    videoProjects: [],
    selectedVideoProject: null,
    videoProjectsLoading: false,
    videoProjectDetailLoading: false,
    audioJobId: null,
    audioPollingTimer: null,
    audioPollingToken: null,
    audioPollingInFlight: false,
    audioPollingErrorStreak: 0,
    audioStreamController: null,
    audioRunning: false,
    audioJobs: {},
    audioJobOrder: [],
    dismissedAudioJobs: new Set(),
    audioQueueSyncTimer: null,
    audioQueueSyncInFlight: false,
    approvalAutoRefreshTimer: null,
    radar: null,
    subtitles2,
  };
}
