import {
  buildSubtitleCueMarkersRuntime,
  buildSubtitleHealthRuntime,
  buildSubtitleInsertRowRuntime,
  buildSubtitlePreviewUrlRuntime,
  buildSubtitlePreviewPresentationRuntime,
  buildSubtitleProcessingMessageRuntime,
  createSubtitlesRuntimeServices,
  describeSubtitleTranslationEngineRuntime,
  extractSubtitleAnalyzeMetadataRuntime,
  extractSubtitleProgressPercentRuntime,
  formatSubtitleDisplayTimeRuntime,
  mapRemoteSubtitleSegmentsToRowsRuntime,
  normalizeSubtitleMetaValueForStateRuntime,
  parseSubtitleTimeToMsRuntime,
  pickActiveSubtitleCueRuntime,
  resolveSubtitleTimelineSeekMsRuntime,
  resolveSubtitlesModeRuntime,
  resolveSubtitleProgressPercentRuntime,
  validateSubtitleTimingPatchRuntime,
} from './services.js';
import {
  buildSubtitleSelectOptionsMarkupRuntime,
  buildSubtitleSessionHistoryMarkupRuntime,
  buildSubtitleTableRowMarkupRuntime,
  buildSubtitlePreviewTimelineMarkupRuntime,
  buildSubtitlesTableRowsMarkupRuntime,
  getLastSubtitleNonDraftRowIndexRuntime,
  hasSubtitleDraftRowsRuntime,
  normalizeSubtitleMetaValueRuntime,
  resolveSubtitleHistoryToneRuntime,
  resolveSubtitlePreviewDurationMsRuntime,
} from './presentation.js';

export {
  buildSubtitleCueMarkersRuntime,
  buildSubtitleHealthRuntime,
  buildSubtitleInsertRowRuntime,
  buildSubtitlePreviewUrlRuntime,
  buildSubtitlePreviewPresentationRuntime,
  buildSubtitleProcessingMessageRuntime,
  buildSubtitleSelectOptionsMarkupRuntime,
  buildSubtitleSessionHistoryMarkupRuntime,
  buildSubtitleTableRowMarkupRuntime,
  buildSubtitlePreviewTimelineMarkupRuntime,
  buildSubtitlesTableRowsMarkupRuntime,
  describeSubtitleTranslationEngineRuntime,
  extractSubtitleAnalyzeMetadataRuntime,
  extractSubtitleProgressPercentRuntime,
  formatSubtitleDisplayTimeRuntime,
  getLastSubtitleNonDraftRowIndexRuntime,
  hasSubtitleDraftRowsRuntime,
  mapRemoteSubtitleSegmentsToRowsRuntime,
  normalizeSubtitleMetaValueRuntime,
  normalizeSubtitleMetaValueForStateRuntime,
  parseSubtitleTimeToMsRuntime,
  pickActiveSubtitleCueRuntime,
  resolveSubtitleHistoryToneRuntime,
  resolveSubtitlePreviewDurationMsRuntime,
  resolveSubtitleTimelineSeekMsRuntime,
  resolveSubtitlesModeRuntime,
  resolveSubtitleProgressPercentRuntime,
  validateSubtitleTimingPatchRuntime,
};

export function createSubtitlesRuntimeControllers({ hooks }) {
  return createSubtitlesRuntimeServices({ hooks });
}
